sudo: required
services:
  - docker

language: ruby

branches:
  only:
    - master

rvm:
  - "2.5.7"

install:
  - docker-compose -f ./.travis/docker-compose-travis.yml build test-forum

script:
  - docker-compose -f ./.travis/docker-compose-travis.yml run --rm test-forum
